service: ScrumNestAppSync

frameworkVersion: ">=2.8.0 <3.0.0"

package:
  exclude:
    - ./node_modules/**
    - node_modules/**


custom:
  stage: ${opt:stage, 'dev'}
  env: ${file(envs.yml):${self:custom.stage}}
  fromEmail: ${opt:email, 'Scrum Nest<no-reply@scrumnest.com>'}

  output:
    file: output.json

  pythonRequirements:
    dockerizePip: false
    layer: true

  dynamodb-table: 'scrumnest-${self:custom.stage}'
  s3-upload-bucket-name:
    Fn::Sub: '${AWS::AccountId}-scrumnest-files-${self:custom.stage}'

  userPoolId: !Ref CognitoUserPool
  userPoolName: ${self:custom.env.userPoolName}

  appSync:
    name: ${self:service}-${self:custom.stage}
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId: ${self:custom.userPoolId}
    logConfig:
      loggingRoleArn: { Fn::GetAtt: [AppSyncLoggingServiceRole, Arn] }
      level: ALL
    defaultMappingTemplates:
      request: my.request.template.tpl  # TODO: Make this false and to have direct lambda proxy
      response: my.response.template.tpl  # TODO: Make this false and to have direct lambda proxy
    mappingTemplates:
      -
        dataSource: LambdaProxy
        type: Mutation
        field: createNest
      -
        dataSource: LambdaProxy
        type: Mutation
        field: addNestUser
      -
        dataSource: LambdaProxy
        type: Mutation
        field: removeNestUser
      -
        dataSource: LambdaProxy
        type: Mutation
        field: createStory
      -
        dataSource: LambdaProxy
        type: Query
        field: nest
      -
        dataSource: LambdaProxy
        type: Query
        field: nests
      -
        dataSource: LambdaProxy
        type: Query
        field: story
      -
        dataSource: LambdaProxy
        type: Query
        field: stories
      -
        dataSource: LambdaProxy
        type: Mutation
        field: addStoryAttachment
      -
        dataSource: LambdaProxy
        type: Mutation
        field: addComment
      -
        dataSource: LambdaProxy
        type: Mutation
        field: updateStory
      -
        dataSource: LambdaProxy
        type: Query
        field: users
      -
        dataSource: LambdaProxy
        type: Mutation
        field: deleteStory
      -
        dataSource: LambdaProxy
        type: Mutation
        field: addSprint
    schema: schema.graphql
    dataSources:
      - type: AWS_LAMBDA
        name: LambdaProxy
        description: 'Lambda Proxy to DynamoDB'
        config:
          functionName: graphql
          iamRoleStatements:
            - Effect: "Allow"
              Action:
                - "lambda:InvokeFunction"
              Resource:
                - "*"  # TODO: Change this so that it can only invoke that one lambda but sls is being a PITA


provider:
  name: aws
  runtime: python3.8
  region: ${opt:region, 'us-east-1'}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
        - 'dynamodb:*'
        - 'logs:*'
        - 'cognito-idp:ListUsers'
        - 'ses:SendEmail'
      Resource: '*'

  environment:
    REGION: ${self:provider.region}
    DYNAMO_DB_TABLE_NAME: ${self:custom.dynamodb-table}
    USER_POOL_ID: ${self:custom.userPoolId}
    FROM_EMAIL: ${self:custom.fromEmail}


functions:
  graphql:
    handler: functions.handler.main
    layers:
      - { Ref: PythonRequirementsLambdaLayer }

  postSignUp:
    handler: functions.post-signup.add_usernames_to_nests
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - cognitoUserPool:
          pool: ${self:custom.userPoolName}
          trigger: PostConfirmation
          existing: true


resources:
  - ${file(resources/roles.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
  - ${file(resources/dynamodb-table.yml)}
  - ${file(resources/outputs.yml)}
  - ${file(resources/s3.yml)}

plugins:
   - serverless-stack-output
   - serverless-appsync-plugin
   - serverless-python-requirements
